# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GridDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GridDemo
  pod 'SnapKit', '~> 3.2.0'
  
  pod 'Grid', :path => '../'

  target 'GridDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GridDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
